// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLlnP7ueMzVFsOc8gbW_3eTluqAiSEig',
    appId: '1:254957530147:web:4d667d084dc9a12423d596',
    messagingSenderId: '254957530147',
    projectId: 'ghp-society-ms',
    authDomain: 'ghp-society-ms.firebaseapp.com',
    storageBucket: 'ghp-society-ms.appspot.com',
    measurementId: 'G-C52N4Z8ZGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNLmI5goNLYGFMWXD7caRt0MBK_Sdpa_E',
    appId: '1:254957530147:android:7e42ede66896865923d596',
    messagingSenderId: '254957530147',
    projectId: 'ghp-society-ms',
    storageBucket: 'ghp-society-ms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-sWOYV49KfJ_e372ylZ7WJRYsl3REOPE',
    appId: '1:254957530147:ios:33fb8178fb0146d223d596',
    messagingSenderId: '254957530147',
    projectId: 'ghp-society-ms',
    storageBucket: 'ghp-society-ms.appspot.com',
    iosBundleId: 'com.gsm.ghpSocietyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-sWOYV49KfJ_e372ylZ7WJRYsl3REOPE',
    appId: '1:254957530147:ios:33fb8178fb0146d223d596',
    messagingSenderId: '254957530147',
    projectId: 'ghp-society-ms',
    storageBucket: 'ghp-society-ms.appspot.com',
    iosBundleId: 'com.gsm.ghpSocietyManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlLlnP7ueMzVFsOc8gbW_3eTluqAiSEig',
    appId: '1:254957530147:web:cb8e9e95eedcff7023d596',
    messagingSenderId: '254957530147',
    projectId: 'ghp-society-ms',
    authDomain: 'ghp-society-ms.firebaseapp.com',
    storageBucket: 'ghp-society-ms.appspot.com',
    measurementId: 'G-V8QLRJ0NRP',
  );
}
